import os

DEFAULT_MAX_SUBTASK_DEPTH = 3
ACCESS_TOKEN_EXPIRE_MINUTES = 60
REFRESH_TOKEN_EXPIRE_DAYS = 7
DEFAULT_HABIT_LOG_LOOKBACK_DAYS = 30
DEFAULT_COMPLETED_TASK_LOOKBACK_DAYS = 90
ALGORITHM = "HS256"
SECRET_KEY = os.environ.get("SECRET_KEY", "chiave_di_fallback_se_manca_env")
