"""add superuser flags to users

Revision ID: 13e43b924a2d
Revises: beb0e7919e37
Create Date: 2026-06-26 19:33:49.735324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13e43b924a2d'
down_revision: Union[str, Sequence[str], None] = 'beb0e7919e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'must_change_password')
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###
