"""initial schema

Revision ID: 69f41f73e3c4
Revises: 
Create Date: 2026-06-26 16:33:12.424779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69f41f73e3c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('key', sa.String(length=100), nullable=False, comment="Chiave univoca dell'impostazione"),
    sa.Column('value', sa.Text(), nullable=False, comment='Valore salvato in formato stringa (da castare a runtime)'),
    sa.Column('descrizione', sa.Text(), nullable=True, comment='Spiegazione del parametro'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('config_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code_type', sa.String(length=64), nullable=False),
    sa.Column('code_value', sa.String(length=64), nullable=False),
    sa.Column('code_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_type', 'code_value', name='ux_config_codes_type_value')
    )
    op.create_index('ix_config_codes_active', 'config_codes', ['active'], unique=False)
    op.create_index(op.f('ix_config_codes_code_type'), 'config_codes', ['code_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('max_subtask_depth_user', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index('ix_users_username_lower_unique', 'users', [sa.literal_column('lower(username)')], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('colore', sa.String(length=7), nullable=True),
    sa.Column('genre', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.create_table('countdowns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('immagine_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reopened_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active', 'closed')", name='ck_countdowns_status_valid'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countdowns_user_id'), 'countdowns', ['user_id'], unique=False)
    op.create_index('ix_countdowns_user_status', 'countdowns', ['user_id', 'status'], unique=False)
    op.create_index('ix_countdowns_user_target_date', 'countdowns', ['user_id', 'target_date'], unique=False)
    op.create_table('daily_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data_riferimento', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('testo', sa.Text(), nullable=False),
    sa.Column('immagine_url', sa.String(length=1024), nullable=True),
    sa.CheckConstraint("tipo IN ('Obiettivo', 'Priorità', 'Nota')", name='ck_daily_entries_tipo_valid'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_daily_entries_user_data', 'daily_entries', ['user_id', 'data_riferimento'], unique=False)
    op.create_index('ix_daily_entries_user_tipo_data', 'daily_entries', ['user_id', 'tipo', 'data_riferimento'], unique=False)
    op.create_index('ux_daily_entries_one_goal_per_day', 'daily_entries', ['user_id', 'data_riferimento'], unique=True, postgresql_where=sa.text("tipo = 'Obiettivo'"))
    op.create_table('habits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('titolo', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=1), nullable=False),
    sa.Column('rrule', sa.String(length=255), nullable=True),
    sa.Column('immagine_url', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_habits_user', 'habits', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['notification_type_id'], ['config_codes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_notification_type_id'), 'notifications', ['notification_type_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('shared_activity_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module_code_id', sa.Integer(), nullable=False),
    sa.Column('entity_type_id', sa.Integer(), nullable=False),
    sa.Column('action_type_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=False),
    sa.Column('performed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_before', sa.Text(), nullable=True),
    sa.Column('payload_after', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['action_type_id'], ['config_codes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['entity_type_id'], ['config_codes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['module_code_id'], ['config_codes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_activity_log_action_type_id'), 'shared_activity_log', ['action_type_id'], unique=False)
    op.create_index(op.f('ix_shared_activity_log_created_at'), 'shared_activity_log', ['created_at'], unique=False)
    op.create_index('ix_shared_activity_log_entity', 'shared_activity_log', ['module_code_id', 'entity_type_id', 'entity_id'], unique=False)
    op.create_index(op.f('ix_shared_activity_log_entity_id'), 'shared_activity_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_shared_activity_log_entity_type_id'), 'shared_activity_log', ['entity_type_id'], unique=False)
    op.create_index(op.f('ix_shared_activity_log_module_code_id'), 'shared_activity_log', ['module_code_id'], unique=False)
    op.create_index(op.f('ix_shared_activity_log_performed_by_user_id'), 'shared_activity_log', ['performed_by_user_id'], unique=False)
    op.create_table('shopping_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['config_codes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_groups_status_id'), 'shopping_groups', ['status_id'], unique=False)
    op.create_index(op.f('ix_shopping_groups_user_id'), 'shopping_groups', ['user_id'], unique=False)
    op.create_table('shopping_suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_normalized', sa.String(length=255), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['status_id'], ['config_codes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_suppliers_created_by_user_id'), 'shopping_suppliers', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_shopping_suppliers_name_normalized'), 'shopping_suppliers', ['name_normalized'], unique=False)
    op.create_index(op.f('ix_shopping_suppliers_status_id'), 'shopping_suppliers', ['status_id'], unique=False)
    op.create_index(op.f('ix_shopping_suppliers_updated_by_user_id'), 'shopping_suppliers', ['updated_by_user_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titolo', sa.String(length=255), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('data_inizio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_fine', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tutto_il_giorno', sa.Boolean(), nullable=False),
    sa.Column('luogo', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rrule', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_data_inizio'), 'events', ['data_inizio'], unique=False)
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_table('habit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('data_riferimento', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'data_riferimento', name='uix_habit_log_date')
    )
    op.create_index('idx_habit_log_habit_date', 'habit_log', ['habit_id', 'data_riferimento'], unique=False)
    op.create_table('habit_period',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('data_inizio', sa.Date(), nullable=False),
    sa.Column('data_fine', sa.Date(), nullable=True),
    sa.Column('target', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_habit_period_habit_data_inizio', 'habit_period', ['habit_id', 'data_inizio'], unique=False)
    op.create_index('idx_habit_period_habit_id', 'habit_period', ['habit_id'], unique=False)
    op.create_table('shopping_group_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('added_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['shopping_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['config_codes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='ux_shopping_group_members_group_user')
    )
    op.create_index(op.f('ix_shopping_group_members_added_by_user_id'), 'shopping_group_members', ['added_by_user_id'], unique=False)
    op.create_index(op.f('ix_shopping_group_members_group_id'), 'shopping_group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_shopping_group_members_role_id'), 'shopping_group_members', ['role_id'], unique=False)
    op.create_index(op.f('ix_shopping_group_members_user_id'), 'shopping_group_members', ['user_id'], unique=False)
    op.create_table('shopping_lists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('visibility_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['shopping_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_id'], ['config_codes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visibility_id'], ['config_codes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_lists_group_id'), 'shopping_lists', ['group_id'], unique=False)
    op.create_index(op.f('ix_shopping_lists_status_id'), 'shopping_lists', ['status_id'], unique=False)
    op.create_index(op.f('ix_shopping_lists_user_id'), 'shopping_lists', ['user_id'], unique=False)
    op.create_index(op.f('ix_shopping_lists_visibility_id'), 'shopping_lists', ['visibility_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titolo', sa.String(length=255), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('data_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_scadenza', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priorita', sa.String(length=10), nullable=False),
    sa.Column('luogo', sa.String(length=255), nullable=True),
    sa.Column('fatto', sa.Boolean(), nullable=False),
    sa.Column('data_fatto', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_parent_id'), 'tasks', ['parent_id'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('shopping_list_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shopping_list_id', sa.Integer(), nullable=False),
    sa.Column('name_original', sa.String(length=255), nullable=False),
    sa.Column('name_normalized', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('is_purchased', sa.Boolean(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purchased_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchased_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['shopping_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_id'], ['config_codes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['config_codes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_list_items_created_by_user_id'), 'shopping_list_items', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_shopping_list_items_name_normalized'), 'shopping_list_items', ['name_normalized'], unique=False)
    op.create_index(op.f('ix_shopping_list_items_purchased_by_user_id'), 'shopping_list_items', ['purchased_by_user_id'], unique=False)
    op.create_index(op.f('ix_shopping_list_items_shopping_list_id'), 'shopping_list_items', ['shopping_list_id'], unique=False)
    op.create_index(op.f('ix_shopping_list_items_status_id'), 'shopping_list_items', ['status_id'], unique=False)
    op.create_index(op.f('ix_shopping_list_items_unit_id'), 'shopping_list_items', ['unit_id'], unique=False)
    op.create_index(op.f('ix_shopping_list_items_updated_by_user_id'), 'shopping_list_items', ['updated_by_user_id'], unique=False)
    op.create_table('shopping_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shopping_list_id', sa.Integer(), nullable=False),
    sa.Column('shopping_list_item_id', sa.Integer(), nullable=False),
    sa.Column('product_name_original', sa.String(length=255), nullable=True),
    sa.Column('product_name_normalized', sa.String(length=255), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('offer_flag_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_id'], ['config_codes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['offer_flag_id'], ['config_codes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shopping_list_id'], ['shopping_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shopping_list_item_id'], ['shopping_list_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['shopping_suppliers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_prices_created_by_user_id'), 'shopping_prices', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_shopping_prices_product_name_normalized'), 'shopping_prices', ['product_name_normalized'], unique=False)
    op.create_index(op.f('ix_shopping_prices_purchase_date'), 'shopping_prices', ['purchase_date'], unique=False)
    op.create_index(op.f('ix_shopping_prices_shopping_list_id'), 'shopping_prices', ['shopping_list_id'], unique=False)
    op.create_index(op.f('ix_shopping_prices_shopping_list_item_id'), 'shopping_prices', ['shopping_list_item_id'], unique=False)
    op.create_index(op.f('ix_shopping_prices_supplier_id'), 'shopping_prices', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_shopping_prices_updated_by_user_id'), 'shopping_prices', ['updated_by_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopping_prices_updated_by_user_id'), table_name='shopping_prices')
    op.drop_index(op.f('ix_shopping_prices_supplier_id'), table_name='shopping_prices')
    op.drop_index(op.f('ix_shopping_prices_shopping_list_item_id'), table_name='shopping_prices')
    op.drop_index(op.f('ix_shopping_prices_shopping_list_id'), table_name='shopping_prices')
    op.drop_index(op.f('ix_shopping_prices_purchase_date'), table_name='shopping_prices')
    op.drop_index(op.f('ix_shopping_prices_product_name_normalized'), table_name='shopping_prices')
    op.drop_index(op.f('ix_shopping_prices_created_by_user_id'), table_name='shopping_prices')
    op.drop_table('shopping_prices')
    op.drop_index(op.f('ix_shopping_list_items_updated_by_user_id'), table_name='shopping_list_items')
    op.drop_index(op.f('ix_shopping_list_items_unit_id'), table_name='shopping_list_items')
    op.drop_index(op.f('ix_shopping_list_items_status_id'), table_name='shopping_list_items')
    op.drop_index(op.f('ix_shopping_list_items_shopping_list_id'), table_name='shopping_list_items')
    op.drop_index(op.f('ix_shopping_list_items_purchased_by_user_id'), table_name='shopping_list_items')
    op.drop_index(op.f('ix_shopping_list_items_name_normalized'), table_name='shopping_list_items')
    op.drop_index(op.f('ix_shopping_list_items_created_by_user_id'), table_name='shopping_list_items')
    op.drop_table('shopping_list_items')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_parent_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_shopping_lists_visibility_id'), table_name='shopping_lists')
    op.drop_index(op.f('ix_shopping_lists_user_id'), table_name='shopping_lists')
    op.drop_index(op.f('ix_shopping_lists_status_id'), table_name='shopping_lists')
    op.drop_index(op.f('ix_shopping_lists_group_id'), table_name='shopping_lists')
    op.drop_table('shopping_lists')
    op.drop_index(op.f('ix_shopping_group_members_user_id'), table_name='shopping_group_members')
    op.drop_index(op.f('ix_shopping_group_members_role_id'), table_name='shopping_group_members')
    op.drop_index(op.f('ix_shopping_group_members_group_id'), table_name='shopping_group_members')
    op.drop_index(op.f('ix_shopping_group_members_added_by_user_id'), table_name='shopping_group_members')
    op.drop_table('shopping_group_members')
    op.drop_index('idx_habit_period_habit_id', table_name='habit_period')
    op.drop_index('idx_habit_period_habit_data_inizio', table_name='habit_period')
    op.drop_table('habit_period')
    op.drop_index('idx_habit_log_habit_date', table_name='habit_log')
    op.drop_table('habit_log')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_index(op.f('ix_events_data_inizio'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_shopping_suppliers_updated_by_user_id'), table_name='shopping_suppliers')
    op.drop_index(op.f('ix_shopping_suppliers_status_id'), table_name='shopping_suppliers')
    op.drop_index(op.f('ix_shopping_suppliers_name_normalized'), table_name='shopping_suppliers')
    op.drop_index(op.f('ix_shopping_suppliers_created_by_user_id'), table_name='shopping_suppliers')
    op.drop_table('shopping_suppliers')
    op.drop_index(op.f('ix_shopping_groups_user_id'), table_name='shopping_groups')
    op.drop_index(op.f('ix_shopping_groups_status_id'), table_name='shopping_groups')
    op.drop_table('shopping_groups')
    op.drop_index(op.f('ix_shared_activity_log_performed_by_user_id'), table_name='shared_activity_log')
    op.drop_index(op.f('ix_shared_activity_log_module_code_id'), table_name='shared_activity_log')
    op.drop_index(op.f('ix_shared_activity_log_entity_type_id'), table_name='shared_activity_log')
    op.drop_index(op.f('ix_shared_activity_log_entity_id'), table_name='shared_activity_log')
    op.drop_index('ix_shared_activity_log_entity', table_name='shared_activity_log')
    op.drop_index(op.f('ix_shared_activity_log_created_at'), table_name='shared_activity_log')
    op.drop_index(op.f('ix_shared_activity_log_action_type_id'), table_name='shared_activity_log')
    op.drop_table('shared_activity_log')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_habits_user', table_name='habits')
    op.drop_table('habits')
    op.drop_index('ux_daily_entries_one_goal_per_day', table_name='daily_entries', postgresql_where=sa.text("tipo = 'Obiettivo'"))
    op.drop_index('ix_daily_entries_user_tipo_data', table_name='daily_entries')
    op.drop_index('ix_daily_entries_user_data', table_name='daily_entries')
    op.drop_table('daily_entries')
    op.drop_index('ix_countdowns_user_target_date', table_name='countdowns')
    op.drop_index('ix_countdowns_user_status', table_name='countdowns')
    op.drop_index(op.f('ix_countdowns_user_id'), table_name='countdowns')
    op.drop_table('countdowns')
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index('ix_users_username_lower_unique', table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_config_codes_code_type'), table_name='config_codes')
    op.drop_index('ix_config_codes_active', table_name='config_codes')
    op.drop_table('config_codes')
    op.drop_table('config')
    # ### end Alembic commands ###
